const OK_STATUS_CODE = 200;
const CREATED_STATUS_CODE = 201;
const ACCEPTED_STATUS_CODE = 200;
const BAD_REQUEST_STATUS_CODE = 400;
const UNAUTHORIZED_STATUS_CODE = 401 ;
const FORBIDDEN_STATUS_CODE = 403;
const NOT_FOUND_STATUS_CODE = 404;
const METHOD_NOT_ALLOWD_STATUS_CODE = 405;
const TOO_MANY_REQUEST_STATUS_CODE = 429;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;
const BAD_GATEWAY_STATUS_CODE  = 502;
const GATEWAY_TIMEOUT_STATUS_CODE = 504;

module.exports = {
    OK_STATUS_CODE,
    CREATED_STATUS_CODE,
    ACCEPTED_STATUS_CODE,
    BAD_REQUEST_STATUS_CODE,
    UNAUTHORIZED_STATUS_CODE,
    FORBIDDEN_STATUS_CODE,
    NOT_FOUND_STATUS_CODE,
    METHOD_NOT_ALLOWD_STATUS_CODE,
    TOO_MANY_REQUEST_STATUS_CODE,
    INTERNAL_SERVER_ERROR_STATUS_CODE,
    BAD_GATEWAY_STATUS_CODE,
    GATEWAY_TIMEOUT_STATUS_CODE,
}